version: 2.1
defaults: &defaults
  working_directory: ~/python_tracer
  docker:
  - image: circleci/python:3.7

commands:
  install_java:
    description: "Install java 8 JDK & maven"
    steps:
      - run:
          command: |
            sudo apt-get update
            sudo apt-get install openjdk-8-jdk
            sudo update-alternatives --config java
            sudo apt install maven
  checkout_credentials:
    description: "Checkout credentials"
    steps:
      - run:
          command: |
            cd ..
            git clone git@github.com:lumigo-io/common-resources.git
  checkout_utils:
    description: "Checkout various utilities"
    steps:
      - run:
          command: |
            mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            cd ..
            git clone git@github.com:lumigo-io/common-resources.git
      - run:
          command: |
            cd ..
            git clone git@github.com:lumigo-io/utils.git
  checkout_code:
    description: "Checkout code and test it"
    steps:
      - checkout
      - run:
            # Avoid annoying double runs after deploy.
            # See https://discuss.circleci.com/t/job-runs-even-when-tags-ignore-filter-is-triggered-when-combined-with-branches-only/20664
            name: Check if tagged
            command: |
              tags=$(git tag -l --points-at HEAD)
              echo "Tags $tags"
              if [[ ! -z "$tags" ]]
              then
                echo "A tagged commit, skip..."
                circleci step halt
              fi
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            cd src/
            python setup.py develop
            cd ..
      # https://discuss.circleci.com/t/activate-python-virtualenv-for-whole-job/14434
      - run: echo "source venv/bin/activate" >> $BASH_ENV

      - run: pip install pytest-cov
      - run: pip install pre-commit
      - run: pre-commit install
      - run: curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
      - run: sudo apt install nodejs
      - run: sudo npm i -g serverless@1.41.1

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}

workflows:
  test-deploy:
    jobs:
    - test:
        filters:
          branches:
            ignore: master
    - integration-test:
        filters:
          branches:
            ignore: master
        requires:
          - test
    - deploy:
        filters:
          branches:
            only: master
  midnight-deploy: # Deploy everyday to make sure the latest nodejs tracer is deployed
    triggers:
      - schedule:
          cron: "0 8 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - deploy

jobs:
  test:
    <<: *defaults
    steps:
      - checkout_utils
      - checkout_code
      # run tests!
      - run: mkdir ~/.aws && printf "[default] \n aws_access_key_id=dummy \n aws_secret_access_key=dummy" > ~/.aws/credentials
      - run: export AWS_DEFAULT_REGION=us-west-2 && export USER=CICD && pytest --cov=./
      - run: export AWS_DEFAULT_REGION=us-west-2 && export USER=CICD && ./scripts/checks.sh
      - run: bash <(curl -s https://codecov.io/bash)

  integration-test:
    <<: *defaults
    steps:
      - checkout_utils
      - checkout_code
      - install_java
      - run: sudo pip install awscli
      - run: ./scripts/ci_deploy.sh
      - run: cd ../integration-tests && npm i
      - run: sudo npm install -g recursive-install
      - run: cd ../integration-tests && ./scripts/prepare_env.sh
      - run: cd ../integration-tests && ./scripts/deploy.sh
      - run: cd ../integration-tests && npm run test

  deploy:
    <<: *defaults
    steps:
      - checkout_utils
      - checkout_code
      # Set environment variables to allow unit testing runs. See https://github.com/spulec/moto/issues/1941
      - run: mkdir ~/.aws && printf "[default] \n aws_access_key_id=dummy \n aws_secret_access_key=dummy" > ~/.aws/credentials
      - run: export AWS_DEFAULT_REGION=us-west-2 && export USER=CICD && pytest --cov=./
      - run: bash <(curl -s https://codecov.io/bash)
      - run: sudo pip install awscli
      - run: ./scripts/bd_to_prod.sh
