version: 2.1
defaults: &defaults
  working_directory: ~/lumigo_tracer
  docker:
  - image: circleci/python:3.7

commands:
  checkout_code:
    description: "Checkout code and test it"
    steps:
      - checkout
      - run:
            # Avoid annoying double runs after deploy.
            # See https://discuss.circleci.com/t/job-runs-even-when-tags-ignore-filter-is-triggered-when-combined-with-branches-only/20664
            name: Check if tagged
            command: |
              tags=$(git tag -l --points-at HEAD)
              echo "Tags $tags"
              if [[ ! -z "$tags" ]]
              then
                echo "A tagged commit, skip..."
                circleci step halt
              fi
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "setup.py" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .

      # https://discuss.circleci.com/t/activate-python-virtualenv-for-whole-job/14434
      - run: echo "source venv/bin/activate" >> $BASH_ENV

      - run: pip install pytest-cov
      - run: pip install pre-commit
      - run: pre-commit install

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "setup.py" }}

workflows:
  test-deploy:
    jobs:
    - test
    - deploy:
        requires:
        - test
        filters:
          branches:
            only: master

jobs:
  test:
    <<: *defaults
    steps:
      - checkout_code
      # run tests!
      - run: pytest --cov=./
      - run: ./scripts/checks.sh
      - run: bash <(curl -s https://codecov.io/bash)


  deploy:
    <<: *defaults
    steps:
      - checkout_code
      - run: ./scripts/bd_to_prod.sh